In [1]:
import os 
import glob
import pandas as pd

In [2]:
files = sorted(glob.glob('../data/raw/*.csv'))
datasets = {}

for f in files:
    name = os.path.basename(f).replace('.csv', '')

    if name.startswith('nav_'):
        continue

    try:
        datasets[name] = pd.read_csv(f)
    except UnicodeDecodeError:
        datasets[name] = pd.read_csv(f, encoding='ISO-8859-1')

print(len(datasets))
print(list(datasets.keys()))

10
['1788499980509-304c1255-08_investor_transactions', '1788499982117-e3d6ab98-09_portfolio_holdings', '1788499982615-f9647ab2-10_benchmark_indices', '1788499983024-b042c300-01_fund_master', '1788499983331-4389156d-02_nav_history', '1788499984134-b0cbf625-03_aum_by_fund_house', '1788499984405-d702a6c6-04_monthly_sip_inflows', '1788499984721-4b860901-05_category_inflows', '1788499985036-da4a0c4a-06_industry_folio_count', '1788499985420-bb134abf-07_scheme_performance']

In [3]:
for name, df in datasets.items():
    print(name)
    print(list(df.columns))
    print()

1788499980509-304c1255-08_investor_transactions
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

1788499982117-e3d6ab98-09_portfolio_holdings
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

1788499982615-f9647ab2-10_benchmark_indices
['date', 'index_name', 'close_value']

1788499983024-b042c300-01_fund_master
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

1788499983331-4389156d-02_nav_history
['amfi_code', 'date', 'nav']

1788499984134-b0cbf625-03_aum_by_fund_house
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

1788499984405-d702a6c6-04_monthly_sip_inflows
['month', 'sip_inflow_crore', 'active_sip_accounts_crore', 'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct']

1788499984721-4b860901-05_category_inflows
['month', 'category', 'net_inflow_crore']

1788499985036-da4a0c4a-06_industry_folio_count
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

1788499985420-bb134abf-07_scheme_performance
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [6]:
master = datasets['PUT_FILE_NAME_HERE']

print(master.shape)
print(master.dtypes)
master.head()

KeyError: 'PUT_FILE_NAME_HERE'

In [7]:
print(list(datasets.keys()))

['1788499980509-304c1255-08_investor_transactions', '1788499982117-e3d6ab98-09_portfolio_holdings', '1788499982615-f9647ab2-10_benchmark_indices', '1788499983024-b042c300-01_fund_master', '1788499983331-4389156d-02_nav_history', '1788499984134-b0cbf625-03_aum_by_fund_house', '1788499984405-d702a6c6-04_monthly_sip_inflows', '1788499984721-4b860901-05_category_inflows', '1788499985036-da4a0c4a-06_industry_folio_count', '1788499985420-bb134abf-07_scheme_performance']

In [8]:
for name, df in datasets.items():
    print(name)
    print(list(df.columns))
    print()

1788499980509-304c1255-08_investor_transactions
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

1788499982117-e3d6ab98-09_portfolio_holdings
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

1788499982615-f9647ab2-10_benchmark_indices
['date', 'index_name', 'close_value']

1788499983024-b042c300-01_fund_master
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

1788499983331-4389156d-02_nav_history
['amfi_code', 'date', 'nav']

1788499984134-b0cbf625-03_aum_by_fund_house
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

1788499984405-d702a6c6-04_monthly_sip_inflows
['month', 'sip_inflow_crore', 'active_sip_accounts_crore', 'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct']

1788499984721-4b860901-05_category_inflows
['month', 'category', 'net_inflow_crore']

1788499985036-da4a0c4a-06_industry_folio_count
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

1788499985420-bb134abf-07_scheme_performance
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [14]:
master = datasets['fund_master']

print(master.shape)
print(master.dtypes)
master.head()

KeyError: 'fund_master'

In [15]:
master = datasets['1788499983024-b042c300-01_fund_master']

print(master.shape)
print(master.dtypes)
master.head()

(40, 15)
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [16]:
files = sorted(glob.glob('../data/raw/*.csv'))
datasets = {}

for f in files:
    name = os.path.basename(f).replace('.csv', '')

    if name.startswith('nav_'):
        continue

    short_name = name.split('-', 2)[-1]

    try:
        datasets[short_name] = pd.read_csv(f)
    except UnicodeDecodeError:
        datasets[short_name] = pd.read_csv(f, encoding='ISO-8859-1')

print(len(datasets))
print(list(datasets.keys()))

10
['08_investor_transactions', '09_portfolio_holdings', '10_benchmark_indices', '01_fund_master', '02_nav_history', '03_aum_by_fund_house', '04_monthly_sip_inflows', '05_category_inflows', '06_industry_folio_count', '07_scheme_performance']

In [17]:
master = datasets['01_fund_master']

print(master.shape)
print(master.dtypes)
master.head()

(40, 15)
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [18]:
CODE_COL = 'amfi_code'
NAME_COL = 'scheme_name'
FUND_HOUSE_COL = 'fund_house'
CATEGORY_COL = 'category'
SUBCATEGORY_COL = 'sub_category'
RISK_COL = 'risk_category'

In [19]:
print('Number of fund houses:', master[FUND_HOUSE_COL].nunique())
print()
print(sorted(master[FUND_HOUSE_COL].dropna().unique()))
print()
print(master[FUND_HOUSE_COL].value_counts(dropna=False))

Number of fund houses: 10

['Aditya Birla Sun Life MF', 'Axis Mutual Fund', 'DSP Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF', 'Kotak Mahindra MF', 'Mirae Asset MF', 'Nippon India MF', 'SBI Mutual Fund', 'UTI Mutual Fund']

fund_house
SBI Mutual Fund             5
HDFC Mutual Fund            5
ICICI Prudential MF         5
Nippon India MF             5
Kotak Mahindra MF           4
Axis Mutual Fund            4
Aditya Birla Sun Life MF    3
UTI Mutual Fund             3
Mirae Asset MF              3
DSP Mutual Fund             3
Name: count, dtype: int64

In [20]:
columns_to_explore = {
    'Category': CATEGORY_COL,
    'Sub-category': SUBCATEGORY_COL,
    'Risk grade': RISK_COL,
}

for title, col in columns_to_explore.items():
    print('=' * 60)
    print(title, '| column:', col)
    print('=' * 60)
    print('Unique values:', master[col].nunique())
    print('Missing values:', master[col].isnull().sum())
    print()
    print(sorted(master[col].dropna().unique()))
    print()
    print(master[col].value_counts(dropna=False))
    print()

============================================================
Category | column: category
============================================================
Unique values: 2
Missing values: 0

['Debt', 'Equity']

category
Equity    34
Debt       6
Name: count, dtype: int64

============================================================
Sub-category | column: sub_category
============================================================
Unique values: 12
Missing values: 0

['ELSS', 'Flexi Cap', 'Gilt', 'Index', 'Index/ETF', 'Large & Mid Cap', 'Large Cap', 'Liquid', 'Mid Cap', 'Short Duration', 'Small Cap', 'Value']

sub_category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Short Duration      1
Value               1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

============================================================
Risk grade | column: risk_category
============================================================
Unique values: 5
Missing values: 0

['High', 'Low', 'Moderate', 'Moderately High', 'Very High']

risk_category
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

In [21]:
master.groupby(CATEGORY_COL)[SUBCATEGORY_COL].unique()

category
Debt                         [Gilt, Short Duration, Liquid]
Equity    [Large Cap, Small Cap, Mid Cap, Value, Index/E...
Name: sub_category, dtype: object

In [22]:
pd.crosstab(master[CATEGORY_COL], master[RISK_COL])

risk_category  High  Low  Moderate  Moderately High  Very High
category
Debt              0    6         0                0          0
Equity            8    0        16                4          6

In [23]:
print('Data type:', master[CODE_COL].dtype)
print('Smallest code:', master[CODE_COL].min())
print('Largest code:', master[CODE_COL].max())
print('Rows:', len(master))
print('Unique codes:', master[CODE_COL].nunique())
print()
print(master[CODE_COL].dropna().astype(int).astype(str).str.len().value_counts())

Data type: int64
Smallest code: 100016
Largest code: 149324
Rows: 40
Unique codes: 40

amfi_code
6    40
Name: count, dtype: int64

In [24]:
by_code = master.sort_values(CODE_COL)

print(by_code[[CODE_COL, NAME_COL]].head(10))
print()
print(by_code[[CODE_COL, NAME_COL]].tail(10))

    amfi_code                                        scheme_name
5      100016          HDFC Top 100 Fund - Regular Plan - Growth
9      100025       HDFC Short Term Debt Fund - Regular - Growth
7      100033  HDFC Mid-Cap Opportunities Fund - Regular - Gr...
28     101206      ABSL Frontline Equity Fund - Regular - Growth
29     101207             ABSL Small Cap Fund - Regular - Growth
30     101208                ABSL Liquid Fund - Regular - Growth
31     102885         UTI Nifty 50 Index Fund - Regular - Growth
32     102886                UTI Mid Cap Fund - Regular - Growth
33     102887              UTI Flexi Cap Fund - Regular - Growth
15     118632     Nippon India Large Cap Fund - Regular - Growth

    amfi_code                                        scheme_name
22     120843             Kotak Flexicap Fund - Regular - Growth
23     120844               Kotak Liquid Fund - Regular - Growth
6      125497           HDFC Top 100 Fund - Direct Plan - Growth
8      125498  HDFC Mid-Cap Opportunities Fund - Direct - Growth
34     148567      Mirae Asset Large Cap Fund - Regular - Growth
35     148568  Mirae Asset Emerging Bluechip Fund - Regular -...
36     148569      Mirae Asset Tax Saver Fund - Regular - Growth
37     149322         DSP Top 100 Equity Fund - Regular - Growth
38     149323                 DSP Midcap Fund - Regular - Growth
39     149324              DSP Small Cap Fund - Regular - Growth

In [25]:
task_codes = [119551, 120503, 118632, 119092, 120841, 125497]

found = master[master[CODE_COL].isin(task_codes)]
print(found[[CODE_COL, NAME_COL, FUND_HOUSE_COL]])

    amfi_code                                     scheme_name  \
0      119551       SBI Bluechip Fund - Regular Plan - Growth
6      125497        HDFC Top 100 Fund - Direct Plan - Growth
10     120503      ICICI Pru Bluechip Fund - Regular - Growth
15     118632  Nippon India Large Cap Fund - Regular - Growth
20     120841          Kotak Bluechip Fund - Regular - Growth
24     119092           Axis Bluechip Fund - Regular - Growth

             fund_house
0       SBI Mutual Fund
6      HDFC Mutual Fund
10  ICICI Prudential MF
15      Nippon India MF
20    Kotak Mahindra MF
24     Axis Mutual Fund